-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.Article exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
id : SelectionSet String SAI.Object.Article
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| -}
title : SelectionSet String SAI.Object.Article
title =
    Object.selectionForField "String" "title" [] Decode.string


{-| -}
text : SelectionSet String SAI.Object.Article
text =
    Object.selectionForField "String" "text" [] Decode.string


{-| -}
author : SelectionSet decodesTo SAI.Object.Profile -> SelectionSet decodesTo SAI.Object.Article
author object_ =
    Object.selectionForCompositeField "author" [] object_ identity


{-| -}
comments : SelectionSet decodesTo SAI.Object.Comment -> SelectionSet (Maybe (List (Maybe decodesTo))) SAI.Object.Article
comments object_ =
    Object.selectionForCompositeField "comments" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
