-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.Date exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
day : SelectionSet Int SAI.Object.Date
day =
    Object.selectionForField "Int" "day" [] Decode.int


{-| -}
month : SelectionSet Int SAI.Object.Date
month =
    Object.selectionForField "Int" "month" [] Decode.int


{-| -}
year : SelectionSet Int SAI.Object.Date
year =
    Object.selectionForField "Int" "year" [] Decode.int
