-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.Event exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.Enum.EventStatus
import SAI.Enum.Frecuency
import SAI.Enum.Status
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
id : SelectionSet (Maybe SAI.ScalarCodecs.Id) SAI.Object.Event
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
name : SelectionSet (Maybe String) SAI.Object.Event
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| -}
startdate : SelectionSet decodesTo SAI.Object.Date -> SelectionSet (Maybe decodesTo) SAI.Object.Event
startdate object_ =
    Object.selectionForCompositeField "startdate" [] object_ (identity >> Decode.nullable)


{-| -}
enddate : SelectionSet decodesTo SAI.Object.Date -> SelectionSet (Maybe decodesTo) SAI.Object.Event
enddate object_ =
    Object.selectionForCompositeField "enddate" [] object_ (identity >> Decode.nullable)


{-| -}
starttime : SelectionSet decodesTo SAI.Object.Time -> SelectionSet (Maybe decodesTo) SAI.Object.Event
starttime object_ =
    Object.selectionForCompositeField "starttime" [] object_ (identity >> Decode.nullable)


{-| -}
endtime : SelectionSet decodesTo SAI.Object.Time -> SelectionSet (Maybe decodesTo) SAI.Object.Event
endtime object_ =
    Object.selectionForCompositeField "endtime" [] object_ (identity >> Decode.nullable)


{-| -}
groups : SelectionSet decodesTo SAI.Object.Group -> SelectionSet (Maybe (List decodesTo)) SAI.Object.Event
groups object_ =
    Object.selectionForCompositeField "groups" [] object_ (identity >> Decode.list >> Decode.nullable)


{-| -}
frecuency : SelectionSet (Maybe SAI.Enum.Frecuency.Frecuency) SAI.Object.Event
frecuency =
    Object.selectionForField "(Maybe Enum.Frecuency.Frecuency)" "frecuency" [] (SAI.Enum.Frecuency.decoder |> Decode.nullable)


{-| -}
fatherevent : SelectionSet (Maybe SAI.ScalarCodecs.Id) SAI.Object.Event
fatherevent =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "fatherevent" [] (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
childrenevent : SelectionSet decodesTo SAI.Object.Event -> SelectionSet (Maybe (List (Maybe decodesTo))) SAI.Object.Event
childrenevent object_ =
    Object.selectionForCompositeField "childrenevent" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
assistants : SelectionSet decodesTo SAI.Object.Person -> SelectionSet (Maybe (List decodesTo)) SAI.Object.Event
assistants object_ =
    Object.selectionForCompositeField "assistants" [] object_ (identity >> Decode.list >> Decode.nullable)


{-| -}
eventstatus : SelectionSet (Maybe SAI.Enum.EventStatus.EventStatus) SAI.Object.Event
eventstatus =
    Object.selectionForField "(Maybe Enum.EventStatus.EventStatus)" "eventstatus" [] (SAI.Enum.EventStatus.decoder |> Decode.nullable)


{-| -}
status : SelectionSet SAI.Enum.Status.Status SAI.Object.Event
status =
    Object.selectionForField "Enum.Status.Status" "status" [] SAI.Enum.Status.decoder
