-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.Group exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.Enum.Status
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
id : SelectionSet SAI.ScalarCodecs.Id SAI.Object.Group
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
name : SelectionSet String SAI.Object.Group
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| -}
members : SelectionSet decodesTo SAI.Object.Person -> SelectionSet (List decodesTo) SAI.Object.Group
members object_ =
    Object.selectionForCompositeField "members" [] object_ (identity >> Decode.list)


{-| -}
status : SelectionSet SAI.Enum.Status.Status SAI.Object.Group
status =
    Object.selectionForField "Enum.Status.Status" "status" [] SAI.Enum.Status.decoder
