-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.LoginResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
find : SelectionSet (Maybe Bool) SAI.Object.LoginResult
find =
    Object.selectionForField "(Maybe Bool)" "find" [] (Decode.bool |> Decode.nullable)


{-| -}
levelaccess : SelectionSet (Maybe String) SAI.Object.LoginResult
levelaccess =
    Object.selectionForField "(Maybe String)" "levelaccess" [] (Decode.string |> Decode.nullable)
