-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.LoginResult exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
id : SelectionSet (Maybe SAI.ScalarCodecs.Id) SAI.Object.LoginResult
id =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "id" [] (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| -}
find : SelectionSet Bool SAI.Object.LoginResult
find =
    Object.selectionForField "Bool" "find" [] Decode.bool


{-| -}
levelaccess : SelectionSet (Maybe String) SAI.Object.LoginResult
levelaccess =
    Object.selectionForField "(Maybe String)" "levelaccess" [] (Decode.string |> Decode.nullable)


{-| -}
groups : SelectionSet decodesTo SAI.Object.Group -> SelectionSet (Maybe (List (Maybe decodesTo))) SAI.Object.LoginResult
groups object_ =
    Object.selectionForCompositeField "groups" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)
