-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.PersonConnection exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
edges : SelectionSet decodesTo SAI.Object.PersonEdge -> SelectionSet (List decodesTo) SAI.Object.PersonConnection
edges object_ =
    Object.selectionForCompositeField "edges" [] object_ (identity >> Decode.list)


{-| -}
nodes : SelectionSet decodesTo SAI.Object.Person -> SelectionSet (List decodesTo) SAI.Object.PersonConnection
nodes object_ =
    Object.selectionForCompositeField "nodes" [] object_ (identity >> Decode.list)


{-| -}
pageInfo : SelectionSet decodesTo SAI.Object.PageInfo -> SelectionSet decodesTo SAI.Object.PersonConnection
pageInfo object_ =
    Object.selectionForCompositeField "pageInfo" [] object_ identity
