-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.PersonEdge exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
node : SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo SAI.Object.PersonEdge
node object_ =
    Object.selectionForCompositeField "node" [] object_ identity


{-| -}
cursor : SelectionSet String SAI.Object.PersonEdge
cursor =
    Object.selectionForField "String" "cursor" [] Decode.string
