-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.Time exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
hour : SelectionSet Int SAI.Object.Time
hour =
    Object.selectionForField "Int" "hour" [] Decode.int


{-| -}
minutes : SelectionSet Int SAI.Object.Time
minutes =
    Object.selectionForField "Int" "minutes" [] Decode.int


{-| -}
seconds : SelectionSet Int SAI.Object.Time
seconds =
    Object.selectionForField "Int" "seconds" [] Decode.int
