-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.Enum.Status
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
id : SelectionSet SAI.ScalarCodecs.Id SAI.Object.User
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| -}
username : SelectionSet String SAI.Object.User
username =
    Object.selectionForField "String" "username" [] Decode.string


{-| -}
password : SelectionSet String SAI.Object.User
password =
    Object.selectionForField "String" "password" [] Decode.string


{-| -}
levelaccess : SelectionSet String SAI.Object.User
levelaccess =
    Object.selectionForField "String" "levelaccess" [] Decode.string


{-| -}
group : SelectionSet decodesTo SAI.Object.Group -> SelectionSet (Maybe decodesTo) SAI.Object.User
group object_ =
    Object.selectionForCompositeField "group" [] object_ (identity >> Decode.nullable)


{-| -}
person : SelectionSet decodesTo SAI.Object.Person -> SelectionSet (Maybe decodesTo) SAI.Object.User
person object_ =
    Object.selectionForCompositeField "person" [] object_ (identity >> Decode.nullable)


{-| -}
status : SelectionSet SAI.Enum.Status.Status SAI.Object.User
status =
    Object.selectionForField "Enum.Status.Status" "status" [] SAI.Enum.Status.decoder
