-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object.User exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.Enum.LevelAccess
import SAI.Enum.Status
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


{-| -}
username : SelectionSet (Maybe String) SAI.Object.User
username =
    Object.selectionForField "(Maybe String)" "username" [] (Decode.string |> Decode.nullable)


{-| -}
password : SelectionSet String SAI.Object.User
password =
    Object.selectionForField "String" "password" [] Decode.string


{-| -}
levelaccess : SelectionSet SAI.Enum.LevelAccess.LevelAccess SAI.Object.User
levelaccess =
    Object.selectionForField "Enum.LevelAccess.LevelAccess" "levelaccess" [] SAI.Enum.LevelAccess.decoder


{-| -}
groups : SelectionSet decodesTo SAI.Object.Group -> SelectionSet (Maybe (List (Maybe decodesTo))) SAI.Object.User
groups object_ =
    Object.selectionForCompositeField "groups" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
status : SelectionSet SAI.Enum.Status.Status SAI.Object.User
status =
    Object.selectionForField "Enum.Status.Status" "status" [] SAI.Enum.Status.decoder
