-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.InputObject exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import SAI.Enum.AtentionNeed
import SAI.Enum.CivilState
import SAI.Enum.Gender
import SAI.Enum.Progress
import SAI.Enum.Status
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


buildCreateGroupInput : CreateGroupInputRequiredFields -> (CreateGroupInputOptionalFields -> CreateGroupInputOptionalFields) -> CreateGroupInput
buildCreateGroupInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { members = Absent, status = Absent }
    in
    { name = required.name, members = optionals.members, status = optionals.status }


type alias CreateGroupInputRequiredFields =
    { name : String }


type alias CreateGroupInputOptionalFields =
    { members : OptionalArgument (List (Maybe String))
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Type for the CreateGroupInput input object.
-}
type alias CreateGroupInput =
    { name : String
    , members : OptionalArgument (List (Maybe String))
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Encode a CreateGroupInput into a value that can be used as an argument.
-}
encodeCreateGroupInput : CreateGroupInput -> Value
encodeCreateGroupInput input =
    Encode.maybeObject
        [ ( "name", Encode.string input.name |> Just ), ( "members", (Encode.string |> Encode.maybe |> Encode.list) |> Encode.optional input.members ), ( "status", Encode.enum SAI.Enum.Status.toString |> Encode.optional input.status ) ]


buildCreatePersonInput : CreatePersonInputRequiredFields -> (CreatePersonInputOptionalFields -> CreatePersonInputOptionalFields) -> CreatePersonInput
buildCreatePersonInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { phone = Absent, progress = Absent, atentionneed = Absent, status = Absent }
    in
    { name = required.name, lastName = required.lastName, email = required.email, address = required.address, phone = optionals.phone, baptized = required.baptized, civilState = required.civilState, gender = required.gender, birthday = required.birthday, progress = optionals.progress, atentionneed = optionals.atentionneed, church = required.church, status = optionals.status }


type alias CreatePersonInputRequiredFields =
    { name : String
    , lastName : String
    , email : String
    , address : String
    , baptized : String
    , civilState : SAI.Enum.CivilState.CivilState
    , gender : SAI.Enum.Gender.Gender
    , birthday : String
    , church : String
    }


type alias CreatePersonInputOptionalFields =
    { phone : OptionalArgument String
    , progress : OptionalArgument SAI.Enum.Progress.Progress
    , atentionneed : OptionalArgument SAI.Enum.AtentionNeed.AtentionNeed
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Type for the CreatePersonInput input object.
-}
type alias CreatePersonInput =
    { name : String
    , lastName : String
    , email : String
    , address : String
    , phone : OptionalArgument String
    , baptized : String
    , civilState : SAI.Enum.CivilState.CivilState
    , gender : SAI.Enum.Gender.Gender
    , birthday : String
    , progress : OptionalArgument SAI.Enum.Progress.Progress
    , atentionneed : OptionalArgument SAI.Enum.AtentionNeed.AtentionNeed
    , church : String
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Encode a CreatePersonInput into a value that can be used as an argument.
-}
encodeCreatePersonInput : CreatePersonInput -> Value
encodeCreatePersonInput input =
    Encode.maybeObject
        [ ( "name", Encode.string input.name |> Just ), ( "lastName", Encode.string input.lastName |> Just ), ( "email", Encode.string input.email |> Just ), ( "address", Encode.string input.address |> Just ), ( "phone", Encode.string |> Encode.optional input.phone ), ( "baptized", Encode.string input.baptized |> Just ), ( "civilState", Encode.enum SAI.Enum.CivilState.toString input.civilState |> Just ), ( "gender", Encode.enum SAI.Enum.Gender.toString input.gender |> Just ), ( "birthday", Encode.string input.birthday |> Just ), ( "progress", Encode.enum SAI.Enum.Progress.toString |> Encode.optional input.progress ), ( "atentionneed", Encode.enum SAI.Enum.AtentionNeed.toString |> Encode.optional input.atentionneed ), ( "church", Encode.string input.church |> Just ), ( "status", Encode.enum SAI.Enum.Status.toString |> Encode.optional input.status ) ]


buildCreateUserInput : CreateUserInputRequiredFields -> (CreateUserInputOptionalFields -> CreateUserInputOptionalFields) -> CreateUserInput
buildCreateUserInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { group = Absent, person = Absent, status = Absent }
    in
    { username = required.username, password = required.password, levelaccess = required.levelaccess, group = optionals.group, person = optionals.person, status = optionals.status }


type alias CreateUserInputRequiredFields =
    { username : String
    , password : String
    , levelaccess : String
    }


type alias CreateUserInputOptionalFields =
    { group : OptionalArgument String
    , person : OptionalArgument String
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Type for the CreateUserInput input object.
-}
type alias CreateUserInput =
    { username : String
    , password : String
    , levelaccess : String
    , group : OptionalArgument String
    , person : OptionalArgument String
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Encode a CreateUserInput into a value that can be used as an argument.
-}
encodeCreateUserInput : CreateUserInput -> Value
encodeCreateUserInput input =
    Encode.maybeObject
        [ ( "username", Encode.string input.username |> Just ), ( "password", Encode.string input.password |> Just ), ( "levelaccess", Encode.string input.levelaccess |> Just ), ( "group", Encode.string |> Encode.optional input.group ), ( "person", Encode.string |> Encode.optional input.person ), ( "status", Encode.enum SAI.Enum.Status.toString |> Encode.optional input.status ) ]


buildUpdateGroupInput : UpdateGroupInputRequiredFields -> (UpdateGroupInputOptionalFields -> UpdateGroupInputOptionalFields) -> UpdateGroupInput
buildUpdateGroupInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { members = Absent }
    in
    { id = required.id, name = required.name, members = optionals.members }


type alias UpdateGroupInputRequiredFields =
    { id : SAI.ScalarCodecs.Id
    , name : String
    }


type alias UpdateGroupInputOptionalFields =
    { members : OptionalArgument (List (Maybe String)) }


{-| Type for the UpdateGroupInput input object.
-}
type alias UpdateGroupInput =
    { id : SAI.ScalarCodecs.Id
    , name : String
    , members : OptionalArgument (List (Maybe String))
    }


{-| Encode a UpdateGroupInput into a value that can be used as an argument.
-}
encodeUpdateGroupInput : UpdateGroupInput -> Value
encodeUpdateGroupInput input =
    Encode.maybeObject
        [ ( "id", (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) input.id |> Just ), ( "name", Encode.string input.name |> Just ), ( "members", (Encode.string |> Encode.maybe |> Encode.list) |> Encode.optional input.members ) ]


buildUpdatePersonInput : UpdatePersonInputRequiredFields -> (UpdatePersonInputOptionalFields -> UpdatePersonInputOptionalFields) -> UpdatePersonInput
buildUpdatePersonInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { name = Absent, lastName = Absent, email = Absent, address = Absent, phone = Absent, baptized = Absent, civilState = Absent, gender = Absent, birthday = Absent, progress = Absent, atentionneed = Absent, church = Absent, status = Absent }
    in
    { id = required.id, name = optionals.name, lastName = optionals.lastName, email = optionals.email, address = optionals.address, phone = optionals.phone, baptized = optionals.baptized, civilState = optionals.civilState, gender = optionals.gender, birthday = optionals.birthday, progress = optionals.progress, atentionneed = optionals.atentionneed, church = optionals.church, status = optionals.status }


type alias UpdatePersonInputRequiredFields =
    { id : SAI.ScalarCodecs.Id }


type alias UpdatePersonInputOptionalFields =
    { name : OptionalArgument String
    , lastName : OptionalArgument String
    , email : OptionalArgument String
    , address : OptionalArgument String
    , phone : OptionalArgument String
    , baptized : OptionalArgument String
    , civilState : OptionalArgument SAI.Enum.CivilState.CivilState
    , gender : OptionalArgument SAI.Enum.Gender.Gender
    , birthday : OptionalArgument String
    , progress : OptionalArgument SAI.Enum.Progress.Progress
    , atentionneed : OptionalArgument SAI.Enum.AtentionNeed.AtentionNeed
    , church : OptionalArgument String
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Type for the UpdatePersonInput input object.
-}
type alias UpdatePersonInput =
    { id : SAI.ScalarCodecs.Id
    , name : OptionalArgument String
    , lastName : OptionalArgument String
    , email : OptionalArgument String
    , address : OptionalArgument String
    , phone : OptionalArgument String
    , baptized : OptionalArgument String
    , civilState : OptionalArgument SAI.Enum.CivilState.CivilState
    , gender : OptionalArgument SAI.Enum.Gender.Gender
    , birthday : OptionalArgument String
    , progress : OptionalArgument SAI.Enum.Progress.Progress
    , atentionneed : OptionalArgument SAI.Enum.AtentionNeed.AtentionNeed
    , church : OptionalArgument String
    , status : OptionalArgument SAI.Enum.Status.Status
    }


{-| Encode a UpdatePersonInput into a value that can be used as an argument.
-}
encodeUpdatePersonInput : UpdatePersonInput -> Value
encodeUpdatePersonInput input =
    Encode.maybeObject
        [ ( "id", (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) input.id |> Just ), ( "name", Encode.string |> Encode.optional input.name ), ( "lastName", Encode.string |> Encode.optional input.lastName ), ( "email", Encode.string |> Encode.optional input.email ), ( "address", Encode.string |> Encode.optional input.address ), ( "phone", Encode.string |> Encode.optional input.phone ), ( "baptized", Encode.string |> Encode.optional input.baptized ), ( "civilState", Encode.enum SAI.Enum.CivilState.toString |> Encode.optional input.civilState ), ( "gender", Encode.enum SAI.Enum.Gender.toString |> Encode.optional input.gender ), ( "birthday", Encode.string |> Encode.optional input.birthday ), ( "progress", Encode.enum SAI.Enum.Progress.toString |> Encode.optional input.progress ), ( "atentionneed", Encode.enum SAI.Enum.AtentionNeed.toString |> Encode.optional input.atentionneed ), ( "church", Encode.string |> Encode.optional input.church ), ( "status", Encode.enum SAI.Enum.Status.toString |> Encode.optional input.status ) ]


buildUpdateUserInput : UpdateUserInputRequiredFields -> (UpdateUserInputOptionalFields -> UpdateUserInputOptionalFields) -> UpdateUserInput
buildUpdateUserInput required fillOptionals =
    let
        optionals =
            fillOptionals
                { group = Absent, person = Absent }
    in
    { id = required.id, username = required.username, password = required.password, levelaccess = required.levelaccess, group = optionals.group, person = optionals.person }


type alias UpdateUserInputRequiredFields =
    { id : SAI.ScalarCodecs.Id
    , username : String
    , password : String
    , levelaccess : String
    }


type alias UpdateUserInputOptionalFields =
    { group : OptionalArgument String
    , person : OptionalArgument String
    }


{-| Type for the UpdateUserInput input object.
-}
type alias UpdateUserInput =
    { id : SAI.ScalarCodecs.Id
    , username : String
    , password : String
    , levelaccess : String
    , group : OptionalArgument String
    , person : OptionalArgument String
    }


{-| Encode a UpdateUserInput into a value that can be used as an argument.
-}
encodeUpdateUserInput : UpdateUserInput -> Value
encodeUpdateUserInput input =
    Encode.maybeObject
        [ ( "id", (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) input.id |> Just ), ( "username", Encode.string input.username |> Just ), ( "password", Encode.string input.password |> Just ), ( "levelaccess", Encode.string input.levelaccess |> Just ), ( "group", Encode.string |> Encode.optional input.group ), ( "person", Encode.string |> Encode.optional input.person ) ]
