-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import SAI.Enum.EventType
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


type alias CreatePersonRequiredArguments =
    { input : SAI.InputObject.CreatePersonInput }


{-|

  - input -

-}
createPerson : CreatePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
createPerson requiredArgs object_ =
    Object.selectionForCompositeField "createPerson" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreatePersonInput ] object_ identity


type alias UpdatePersonRequiredArguments =
    { input : SAI.InputObject.UpdatePersonInput
    , id : SAI.ScalarCodecs.Id
    }


{-|

  - input -
  - id -

-}
updatePerson : UpdatePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
updatePerson requiredArgs object_ =
    Object.selectionForCompositeField "updatePerson" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdatePersonInput, Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias DisablePersonRequiredArguments =
    { id : SAI.ScalarCodecs.Id }


{-|

  - id -

-}
disablePerson : DisablePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
disablePerson requiredArgs object_ =
    Object.selectionForCompositeField "disablePerson" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias EnablePersonRequiredArguments =
    { id : SAI.ScalarCodecs.Id }


{-|

  - id -

-}
enablePerson : EnablePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
enablePerson requiredArgs object_ =
    Object.selectionForCompositeField "enablePerson" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias CreateGroupRequiredArguments =
    { input : SAI.InputObject.CreateGroupInput }


{-|

  - input -

-}
createGroup : CreateGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
createGroup requiredArgs object_ =
    Object.selectionForCompositeField "createGroup" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreateGroupInput ] object_ identity


type alias UpdateGroupRequiredArguments =
    { input : SAI.InputObject.UpdateGroupInput
    , id : SAI.ScalarCodecs.Id
    }


{-|

  - input -
  - id -

-}
updateGroup : UpdateGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
updateGroup requiredArgs object_ =
    Object.selectionForCompositeField "updateGroup" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateGroupInput, Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias DisableGroupRequiredArguments =
    { id : SAI.ScalarCodecs.Id }


{-|

  - id -

-}
disableGroup : DisableGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
disableGroup requiredArgs object_ =
    Object.selectionForCompositeField "disableGroup" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias EnableGroupRequiredArguments =
    { id : SAI.ScalarCodecs.Id }


{-|

  - id -

-}
enableGroup : EnableGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
enableGroup requiredArgs object_ =
    Object.selectionForCompositeField "enableGroup" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias UpdateUserRequiredArguments =
    { input : SAI.InputObject.UpdateUserInput
    , id : SAI.ScalarCodecs.Id
    }


{-|

  - input -
  - id -

-}
updateUser : UpdateUserRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
updateUser requiredArgs object_ =
    Object.selectionForCompositeField "updateUser" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateUserInput, Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias DisableUserRequiredArguments =
    { id : SAI.ScalarCodecs.Id }


{-|

  - id -

-}
disableUser : DisableUserRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
disableUser requiredArgs object_ =
    Object.selectionForCompositeField "disableUser" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias EnableUserRequiredArguments =
    { id : SAI.ScalarCodecs.Id }


{-|

  - id -

-}
enableUser : EnableUserRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
enableUser requiredArgs object_ =
    Object.selectionForCompositeField "enableUser" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias CreateEventRequiredArguments =
    { input : SAI.InputObject.EventInput }


{-|

  - input -

-}
createEvent : CreateEventRequiredArguments -> SelectionSet decodesTo SAI.Object.Event -> SelectionSet decodesTo RootMutation
createEvent requiredArgs object_ =
    Object.selectionForCompositeField "createEvent" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeEventInput ] object_ identity


type alias UpdateEventRequiredArguments =
    { input : SAI.InputObject.UpdateEventInput
    , id : SAI.ScalarCodecs.Id
    }


{-|

  - input -
  - id -

-}
updateEvent : UpdateEventRequiredArguments -> SelectionSet decodesTo SAI.Object.Event -> SelectionSet decodesTo RootMutation
updateEvent requiredArgs object_ =
    Object.selectionForCompositeField "updateEvent" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateEventInput, Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId) ] object_ identity


type alias DisableEventRequiredArguments =
    { id : SAI.ScalarCodecs.Id
    , type_ : SAI.Enum.EventType.EventType
    }


{-|

  - id -
  - type\_ -

-}
disableEvent : DisableEventRequiredArguments -> SelectionSet decodesTo SAI.Object.Event -> SelectionSet decodesTo RootMutation
disableEvent requiredArgs object_ =
    Object.selectionForCompositeField "disableEvent" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId), Argument.required "type" requiredArgs.type_ (Encode.enum SAI.Enum.EventType.toString) ] object_ identity


type alias EnableEventRequiredArguments =
    { id : SAI.ScalarCodecs.Id
    , type_ : SAI.Enum.EventType.EventType
    }


{-|

  - id -
  - type\_ -

-}
enableEvent : EnableEventRequiredArguments -> SelectionSet decodesTo SAI.Object.Event -> SelectionSet decodesTo RootMutation
enableEvent requiredArgs object_ =
    Object.selectionForCompositeField "enableEvent" [ Argument.required "id" requiredArgs.id (SAI.ScalarCodecs.codecs |> SAI.Scalar.unwrapEncoder .codecId), Argument.required "type" requiredArgs.type_ (Encode.enum SAI.Enum.EventType.toString) ] object_ identity
