-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Mutation exposing (..)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)
import SAI.InputObject
import SAI.Interface
import SAI.Object
import SAI.Scalar
import SAI.ScalarCodecs
import SAI.Union


type alias CreatePersonRequiredArguments =
    { input : SAI.InputObject.CreatePersonInput }


{-|

  - input -

-}
createPerson : CreatePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
createPerson requiredArgs object_ =
    Object.selectionForCompositeField "createPerson" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreatePersonInput ] object_ identity


type alias UpdatePersonRequiredArguments =
    { input : SAI.InputObject.UpdatePersonInput }


{-|

  - input -

-}
updatePerson : UpdatePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
updatePerson requiredArgs object_ =
    Object.selectionForCompositeField "updatePerson" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdatePersonInput ] object_ identity


type alias DisablePersonRequiredArguments =
    { input : SAI.InputObject.UpdatePersonInput }


{-|

  - input -

-}
disablePerson : DisablePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
disablePerson requiredArgs object_ =
    Object.selectionForCompositeField "disablePerson" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdatePersonInput ] object_ identity


type alias EnablePersonRequiredArguments =
    { input : SAI.InputObject.UpdatePersonInput }


{-|

  - input -

-}
enablePerson : EnablePersonRequiredArguments -> SelectionSet decodesTo SAI.Object.Person -> SelectionSet decodesTo RootMutation
enablePerson requiredArgs object_ =
    Object.selectionForCompositeField "enablePerson" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdatePersonInput ] object_ identity


type alias CreateGroupRequiredArguments =
    { input : SAI.InputObject.CreateGroupInput }


{-|

  - input -

-}
createGroup : CreateGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
createGroup requiredArgs object_ =
    Object.selectionForCompositeField "createGroup" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreateGroupInput ] object_ identity


type alias UpdateGroupRequiredArguments =
    { input : SAI.InputObject.UpdateGroupInput }


{-|

  - input -

-}
updateGroup : UpdateGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
updateGroup requiredArgs object_ =
    Object.selectionForCompositeField "updateGroup" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateGroupInput ] object_ identity


type alias DisableGroupRequiredArguments =
    { input : SAI.InputObject.UpdateGroupInput }


{-|

  - input -

-}
disableGroup : DisableGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
disableGroup requiredArgs object_ =
    Object.selectionForCompositeField "disableGroup" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateGroupInput ] object_ identity


type alias EnableGroupRequiredArguments =
    { input : SAI.InputObject.UpdateGroupInput }


{-|

  - input -

-}
enableGroup : EnableGroupRequiredArguments -> SelectionSet decodesTo SAI.Object.Group -> SelectionSet decodesTo RootMutation
enableGroup requiredArgs object_ =
    Object.selectionForCompositeField "enableGroup" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateGroupInput ] object_ identity


type alias CreateArticleRequiredArguments =
    { input : SAI.InputObject.CreateArticleInput }


{-|

  - input -

-}
createArticle : CreateArticleRequiredArguments -> SelectionSet decodesTo SAI.Object.Article -> SelectionSet decodesTo RootMutation
createArticle requiredArgs object_ =
    Object.selectionForCompositeField "createArticle" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreateArticleInput ] object_ identity


type alias UpdateArticleRequiredArguments =
    { input : SAI.InputObject.UpdateArticleInput }


{-|

  - input -

-}
updateArticle : UpdateArticleRequiredArguments -> SelectionSet decodesTo SAI.Object.Article -> SelectionSet decodesTo RootMutation
updateArticle requiredArgs object_ =
    Object.selectionForCompositeField "updateArticle" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateArticleInput ] object_ identity


type alias DeleteArticleRequiredArguments =
    { id : String }


{-|

  - id -

-}
deleteArticle : DeleteArticleRequiredArguments -> SelectionSet String RootMutation
deleteArticle requiredArgs =
    Object.selectionForField "String" "deleteArticle" [ Argument.required "id" requiredArgs.id Encode.string ] Decode.string


type alias CreateProfileRequiredArguments =
    { input : SAI.InputObject.CreateProfileInput }


{-|

  - input -

-}
createProfile : CreateProfileRequiredArguments -> SelectionSet decodesTo SAI.Object.Profile -> SelectionSet decodesTo RootMutation
createProfile requiredArgs object_ =
    Object.selectionForCompositeField "createProfile" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreateProfileInput ] object_ identity


type alias UpdateProfileRequiredArguments =
    { input : SAI.InputObject.UpdateProfileInput }


{-|

  - input -

-}
updateProfile : UpdateProfileRequiredArguments -> SelectionSet decodesTo SAI.Object.Profile -> SelectionSet decodesTo RootMutation
updateProfile requiredArgs object_ =
    Object.selectionForCompositeField "updateProfile" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeUpdateProfileInput ] object_ identity


type alias DeleteProfileRequiredArguments =
    { id : String }


{-|

  - id -

-}
deleteProfile : DeleteProfileRequiredArguments -> SelectionSet String RootMutation
deleteProfile requiredArgs =
    Object.selectionForField "String" "deleteProfile" [ Argument.required "id" requiredArgs.id Encode.string ] Decode.string


type alias CreateCommentRequiredArguments =
    { input : SAI.InputObject.CreateCommentInput }


{-|

  - input -

-}
createComment : CreateCommentRequiredArguments -> SelectionSet decodesTo SAI.Object.Comment -> SelectionSet decodesTo RootMutation
createComment requiredArgs object_ =
    Object.selectionForCompositeField "createComment" [ Argument.required "input" requiredArgs.input SAI.InputObject.encodeCreateCommentInput ] object_ identity


type alias DeleteCommentRequiredArguments =
    { id : String }


{-|

  - id -

-}
deleteComment : DeleteCommentRequiredArguments -> SelectionSet String RootMutation
deleteComment requiredArgs =
    Object.selectionForField "String" "deleteComment" [ Argument.required "id" requiredArgs.id Encode.string ] Decode.string
