-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object exposing (..)


type Date
    = Date


type Group
    = Group


type Person
    = Person


type User
    = User
