-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Object exposing (..)


type Date
    = Date


type Event
    = Event


type Group
    = Group


type LoginResult
    = LoginResult


type PageInfo
    = PageInfo


type Person
    = Person


type PersonConnection
    = PersonConnection


type PersonEdge
    = PersonEdge


type Time
    = Time


type User
    = User
