-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.ScalarCodecs exposing (..)

import Json.Decode as Decode exposing (Decoder)
import SAI.Scalar exposing (defaultCodecs)


type alias Id =
    SAI.Scalar.Id


codecs : SAI.Scalar.Codecs Id
codecs =
    SAI.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
