-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module SAI.Enum.Gender exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Male -
  - Female -

-}
type Gender
    = Male
    | Female


list : List Gender
list =
    [ Male, Female ]


decoder : Decoder Gender
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "MALE" ->
                        Decode.succeed Male

                    "FEMALE" ->
                        Decode.succeed Female

                    _ ->
                        Decode.fail ("Invalid Gender type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Gender -> String
toString enum =
    case enum of
        Male ->
            "MALE"

        Female ->
            "FEMALE"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe Gender
fromString enumString =
    case enumString of
        "MALE" ->
            Just Male

        "FEMALE" ->
            Just Female

        _ ->
            Nothing
